[metadata]
name = email-blaster
version = 1.0
author = Rob Weber
author_email = rweber@ecec.com
description = Sends emails based on Jinja templates
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/eau-claire-energy-cooperative/email-blaster
project_urls =
  Bug Tracker = https://github.com/eau-claire-energy-cooperative/email-blaster/issues
classifiers =
  Development Status :: 5 - Production/Stable
  Programming Language :: Python :: 3
  License :: OSI Approved :: GNU General Public License v3 (GPLv3)